### ISSUE TITLE
Tag POMCPOW v0.2.2

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/Registry#6]
@rejuvyesh can you update the registry with this new version of POMCPOW https://github.com/JuliaPOMDP/POMCPOW.jl/releases/tag/v0.2.2

**Comment by zsunberg** [comment]
Or @rejuvyesh , you can tell me how to do it or point me to documentation :)

**Comment by rejuvyesh** [comment]
Sorry for the delay. Too embarrassing the way it's being done right now. I was hoping that since Pkg already merged quite some registry functionality I won't have to do much, so haven't gotten around to automating it 😬.
